CREATE TABLE pm2_5 (
    id INT NOT NULL AUTO_INCREMENT,
    valore FLOAT NOT NULL,
    orario TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE pm10 (
    id INT NOT NULL AUTO_INCREMENT,
    valore FLOAT NOT NULL,
    orario TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
